### ISSUE TITLE
It doesn't seems to work

### ISSUE THREAD

**Issue by rarelygoeshere** [BomberBeetle/RivalsKeyboardRedirector#1]
Hello, I'm trying to implement this for Rivals of Aether to do local 2 players co op with 1 keyboard, but it appears that for whatever reasons, it doesn't seems to be changing anything. I was really hoping this can solve the problem since I would like to play it with my friends, so I hope this can be resolved eventually. Thank you.

**Comment by rarelygoeshere** [comment]
To be specific, I managed to configure it like image attacted, based on a comment from Yazan Saoud in this video below https://www.youtube.com/watch?v=Xhqxn9TLCm8
I've been moving around and testing the buttons, and everything seems to be in order as the desktop registers my keyboard as a controller. However it doesn't allow for another player to move in tandem with one keyboard, so that means the issue still remains. 
Whatever the case, I hope this can be resolved, or if not, for the redirector to receive a new version soon. Thank you.
![screenshot_1685615087](https://github.com/BomberBeetle/RivalsKeyboardRedirector/assets/125143953/d94d7795-db44-40cf-b0fd-f75b0eb015cf)
![screenshot_1685615054](https://github.com/BomberBeetle/RivalsKeyboardRedirector/assets/125143953/cb0c5690-7fd7-4648-bb04-ae87c0b0afc0)

**Comment by BomberBeetle** [comment]
this program is for mapping multiple keyboards to multiple controllers, not a single keyboard to multiple controllers, what you're looking for would rather be something like [UCR](https://github.com/Snoothy/UCR)
